apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-postgres-app
  labels:
      app: postgres-app
spec:
  template:
    metadata:
      name: postgres
      labels:
          app: postgres

    spec:
      containers:
      - name: postgres-container
        image: postgres:15.2
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "avaliacao"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_DB
            value: "avaliacao"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
  replicas: 1
  selector:
    matchLabels:
       app: postgres



#cria o arquivo deployment-postgres.yaml e cola o texto acima

#   kubectl create -f deployment-postgres.yaml
#   kubectl get deployment