apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend-container
      image: felipesoart/avaliacao:backend
      ports:
        - containerPort: 8080
      env:
        - name: DB_HOST_NAME
          value: "192.168.1.5"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "avaliacao"
        - name: DB_PASSWORD
          value: "avaliacao"


#cria o arquivo pod-backend-app.yaml e cola o texto acima
# kubectl get pods -o wide   =  pega o id do postgres e passa apra o valor DB_HOST_NAME
# kubectl create -f pod-backend-app.yaml
# kubectl delete pods backend
# kubectl get pods